services:
  app:
    image: golang:1.26.3-alpine3.23
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
      - terraform-plugins:/root/.terraform.d/plugins
    command: sleep infinity

volumes:
  go-mod-cache:
  go-build-cache:
  terraform-plugins:
