set shell := ["bash", "-uc"]
set positional-arguments

releaser_image := "torii-releaser:latest"

default:
    @just --list

# Print the current release version.
version:
    @cat VERSION

# Build the release-runner image (go + bun + goreleaser + docker-cli). Run
# once after cloning, and again whenever Dockerfile.releaser changes.
release-image:
    docker build -f Dockerfile.releaser -t {{ releaser_image }} .

# Build the embedded Nuxt SPA into web/internal/web/dist.
#
# Runs in its own container with NO docker socket, NO registry credentials and NO
# GITHUB_TOKEN, as the invoking user rather than root. This is the step that
# executes untrusted code: `bun install` plus `bun run generate` runs the Nuxt and
# Vite build graph, i.e. arbitrary build-time plugin code from the whole front-end
# dependency tree. It used to run inside the credentialed releaser container, so
# one malicious dependency version entering bun.lock got the host Docker socket
# (root-equivalent on the maintainer's machine), image push credentials and a
# contents:write GitHub token in a single step — and since checksums.txt is
# generated by that same run and .goreleaser.yml has no signs: block, a tampered
# artifact set verified correctly downstream.
#
# Bun's default refusal to run third-party lifecycle scripts does not help here:
# the execution point is the build, not postinstall.
build-spa:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! docker image inspect {{ releaser_image }} >/dev/null 2>&1; then
        echo "error: {{ releaser_image }} not built. Run: just release-image" >&2
        exit 1
    fi
    echo "==> building SPA (unprivileged, no socket, no credentials)"
    docker run --rm \
        --user "$(id -u):$(id -g)" \
        -e HOME=/tmp \
        -e TORII_VERSION="${TORII_VERSION:-$(cat VERSION)}" \
        -v "$PWD:/workspace" \
        -w /workspace \
        --entrypoint bash \
        {{ releaser_image }} -euc '
            cd web/client
            # Stale .output/.nuxt from a prior run, and the absolute "dist" symlink
            # Nuxt leaves behind (dangling in this container), both survive on the
            # bind-mounted repo. Generating over them staged a short index.html:
            # right size, data cut mid window.__NUXT__.config literal, tail
            # NUL-padded, SPA dead on boot.
            rm -rf .output .nuxt dist
            bun install --frozen-lockfile
            bun run generate
            cd /workspace
            rm -rf web/internal/web/dist
            mkdir -p web/internal/web/dist
            cp -r web/client/.output/public/. web/internal/web/dist/
            # generate gates its own output; this gates what actually gets embedded.
            bun web/client/scripts/verify-output.mjs web/internal/web/dist
            # Nuxt recreates web/client/dist as a symlink to an ABSOLUTE path, which
            # here is /workspace/... — a path that exists only in this container. Left
            # behind on the bind-mounted repo it is a dangling symlink, and the dev
            # container (which mounts the repo at /app) dies on it: the Nuxt dev file
            # watcher fails with ENOENT before the server comes up. The embedded copy
            # above is the artifact that matters, so drop the symlink.
            rm -f web/client/dist
        '

# Cut a release: bump VERSION, tag, push, build the SPA unprivileged, then hand
# off to goreleaser running inside the release-runner container which builds
# cross-platform binaries, builds + pushes the docker image (via the bind-mounted
# host docker socket), and creates the GitHub release with changelog + asset
# uploads.
#
# The SPA build is a separate, uncredentialed step on purpose — see build-spa.
# goreleaser only consumes its staged output.
#
# Requires: docker login (on host), GITHUB_TOKEN in env (or gh auth token).
# KIND is patch (default), minor, or major.
release KIND="patch":
    #!/usr/bin/env bash
    set -euo pipefail

    if ! docker image inspect {{ releaser_image }} >/dev/null 2>&1; then
        echo "error: {{ releaser_image }} not built. Run: just release-image" >&2
        exit 1
    fi
    if ! git diff --quiet || ! git diff --cached --quiet; then
        echo "error: working tree is dirty — commit or stash first" >&2
        exit 1
    fi
    branch=$(git rev-parse --abbrev-ref HEAD)
    if [[ "$branch" != "main" ]]; then
        echo "error: must release from main (currently on '$branch')" >&2
        exit 1
    fi

    cur=$(cat VERSION)
    IFS=. read -r maj min pat <<< "$cur"
    case "{{ KIND }}" in
        major) maj=$((maj + 1)); min=0; pat=0 ;;
        minor) min=$((min + 1)); pat=0 ;;
        patch) pat=$((pat + 1)) ;;
        *) echo "error: KIND must be major|minor|patch (got '{{ KIND }}')" >&2; exit 1 ;;
    esac
    next="${maj}.${min}.${pat}"
    tag="v${next}"
    echo "==> bumping ${cur} → ${next}"

    echo "${next}" > VERSION

    git add VERSION
    git commit -m "chore: release ${tag}"
    git tag -a "${tag}" -m "release ${tag}"

    echo "==> pushing commit + tag"
    git push origin HEAD
    git push origin "${tag}"

    # GITHUB_TOKEN is consumed by goreleaser to publish the release. Fall back
    # to `gh auth token` so users who already have gh logged in don't need to
    # juggle a PAT.
    if [[ -z "${GITHUB_TOKEN:-}" ]] && command -v gh >/dev/null 2>&1; then
        export GITHUB_TOKEN=$(gh auth token)
    fi
    if [[ -z "${GITHUB_TOKEN:-}" ]]; then
        echo "error: GITHUB_TOKEN not set and gh not available" >&2
        exit 1
    fi

    TORII_VERSION="${next}" just build-spa

    echo "==> goreleaser release ${tag}"
    docker run --rm \
        -v "$PWD:/workspace" \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "${HOME}/.docker:/root/.docker:ro" \
        -e GITHUB_TOKEN \
        -e TORII_VERSION="${next}" \
        -w /workspace \
        {{ releaser_image }} \
        release --clean

    echo "==> released ${tag}"

# Dry-run goreleaser without publishing — useful to validate config changes.
release-snapshot:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! docker image inspect {{ releaser_image }} >/dev/null 2>&1; then
        echo "error: {{ releaser_image }} not built. Run: just release-image" >&2
        exit 1
    fi
    TORII_VERSION="$(cat VERSION)-snapshot" just build-spa
    docker run --rm \
        -v "$PWD:/workspace" \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v "${HOME}/.docker:/root/.docker:ro" \
        -e TORII_VERSION="$(cat VERSION)-snapshot" \
        -w /workspace \
        {{ releaser_image }} \
        release --snapshot --clean --skip=publish
