// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAPITokens = `-- name: CountAPITokens :one
SELECT count(*) FROM api_tokens
`

func (q *Queries) CountAPITokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAPITokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, token_prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, created_at
`

type CreateAPITokenParams struct {
	UserID      uuid.UUID
	Name        string
	TokenHash   []byte
	TokenPrefix string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, id)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, created_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash []byte) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one
SELECT id, user_id, name, token_hash, token_prefix, expires_at, last_used_at, created_at FROM api_tokens WHERE id = $1
`

func (q *Queries) GetAPITokenByID(ctx context.Context, id uuid.UUID) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPITokensWithUsers = `-- name: ListAPITokensWithUsers :many
SELECT
    t.id,
    t.user_id,
    t.name,
    t.token_prefix,
    t.expires_at,
    t.last_used_at,
    t.created_at,
    u.username,
    u.email
FROM api_tokens t
JOIN users u ON u.id = t.user_id
ORDER BY t.created_at DESC, t.id ASC
LIMIT $2::int OFFSET $1::int
`

type ListAPITokensWithUsersParams struct {
	Off int32
	Lim int32
}

type ListAPITokensWithUsersRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	TokenPrefix string
	ExpiresAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Username    string
	Email       string
}

func (q *Queries) ListAPITokensWithUsers(ctx context.Context, arg ListAPITokensWithUsersParams) ([]ListAPITokensWithUsersRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensWithUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPITokensWithUsersRow
	for rows.Next() {
		var i ListAPITokensWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenPrefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPITokenLastUsed = `-- name: TouchAPITokenLastUsed :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPITokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPITokenLastUsed, id)
	return err
}
