// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignAPIUserRole = `-- name: AssignAPIUserRole :exec
INSERT INTO api_user_roles (api_user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignAPIUserRoleParams struct {
	ApiUserID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) AssignAPIUserRole(ctx context.Context, arg AssignAPIUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignAPIUserRole, arg.ApiUserID, arg.RoleID)
	return err
}

const countAPIUsers = `-- name: CountAPIUsers :one
SELECT count(*) FROM api_users
`

func (q *Queries) CountAPIUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIUser = `-- name: CreateAPIUser :one
INSERT INTO api_users (name, description, token_hash, token_prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, token_hash, token_prefix, expires_at, last_used_at, disabled, created_at, updated_at
`

type CreateAPIUserParams struct {
	Name        string
	Description string
	TokenHash   []byte
	TokenPrefix string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateAPIUser(ctx context.Context, arg CreateAPIUserParams) (ApiUser, error) {
	row := q.db.QueryRow(ctx, createAPIUser,
		arg.Name,
		arg.Description,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
	)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIUser = `-- name: DeleteAPIUser :exec
DELETE FROM api_users WHERE id = $1
`

func (q *Queries) DeleteAPIUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIUser, id)
	return err
}

const getAPIUserByHash = `-- name: GetAPIUserByHash :one
SELECT id, name, description, token_hash, token_prefix, expires_at, last_used_at, disabled, created_at, updated_at FROM api_users WHERE token_hash = $1
`

func (q *Queries) GetAPIUserByHash(ctx context.Context, tokenHash []byte) (ApiUser, error) {
	row := q.db.QueryRow(ctx, getAPIUserByHash, tokenHash)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIUserByID = `-- name: GetAPIUserByID :one
SELECT id, name, description, token_hash, token_prefix, expires_at, last_used_at, disabled, created_at, updated_at FROM api_users WHERE id = $1
`

func (q *Queries) GetAPIUserByID(ctx context.Context, id uuid.UUID) (ApiUser, error) {
	row := q.db.QueryRow(ctx, getAPIUserByID, id)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIUserRoleIDs = `-- name: GetAPIUserRoleIDs :many
SELECT role_id FROM api_user_roles WHERE api_user_id = $1
`

func (q *Queries) GetAPIUserRoleIDs(ctx context.Context, apiUserID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getAPIUserRoleIDs, apiUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIUserRoles = `-- name: ListAPIUserRoles :many
SELECT r.id, r.name, r.description, r.is_system, r.created_at, r.updated_at FROM roles r
JOIN api_user_roles aur ON aur.role_id = r.id
WHERE aur.api_user_id = $1
ORDER BY r.is_system DESC, r.name ASC
`

func (q *Queries) ListAPIUserRoles(ctx context.Context, apiUserID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listAPIUserRoles, apiUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIUsers = `-- name: ListAPIUsers :many
SELECT id, name, description, token_hash, token_prefix, expires_at, last_used_at, disabled, created_at, updated_at FROM api_users
ORDER BY created_at DESC, id ASC
LIMIT $2::int OFFSET $1::int
`

type ListAPIUsersParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListAPIUsers(ctx context.Context, arg ListAPIUsersParams) ([]ApiUser, error) {
	rows, err := q.db.Query(ctx, listAPIUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiUser
	for rows.Next() {
		var i ApiUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIUserRole = `-- name: RevokeAPIUserRole :exec
DELETE FROM api_user_roles WHERE api_user_id = $1 AND role_id = $2
`

type RevokeAPIUserRoleParams struct {
	ApiUserID uuid.UUID
	RoleID    uuid.UUID
}

func (q *Queries) RevokeAPIUserRole(ctx context.Context, arg RevokeAPIUserRoleParams) error {
	_, err := q.db.Exec(ctx, revokeAPIUserRole, arg.ApiUserID, arg.RoleID)
	return err
}

const touchAPIUserLastUsed = `-- name: TouchAPIUserLastUsed :exec
UPDATE api_users SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIUserLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIUserLastUsed, id)
	return err
}

const updateAPIUserToken = `-- name: UpdateAPIUserToken :one
UPDATE api_users
SET token_hash = $2,
    token_prefix = $3,
    expires_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, token_hash, token_prefix, expires_at, last_used_at, disabled, created_at, updated_at
`

type UpdateAPIUserTokenParams struct {
	ID          uuid.UUID
	TokenHash   []byte
	TokenPrefix string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) UpdateAPIUserToken(ctx context.Context, arg UpdateAPIUserTokenParams) (ApiUser, error) {
	row := q.db.QueryRow(ctx, updateAPIUserToken,
		arg.ID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
	)
	var i ApiUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
