// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_at FROM app_settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO app_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = now()
RETURNING key, value, updated_at
`

type UpsertSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.Key, arg.Value)
	var i AppSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
