// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: handoff_jtis.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const burnHandoffJTI = `-- name: BurnHandoffJTI :one
INSERT INTO handoff_jtis (jti, expires_at)
VALUES ($1, $2)
ON CONFLICT (jti) DO NOTHING
RETURNING jti
`

type BurnHandoffJTIParams struct {
	Jti       string
	ExpiresAt pgtype.Timestamptz
}

// Records a handoff token id as spent and reports whether this call was the first
// to do so. ON CONFLICT DO NOTHING means a second presentation returns no rows,
// i.e. pgx.ErrNoRows, so the winner is decided inside Postgres rather than by a
// read followed by a write. Replaces a process-local map that only bounded replays
// within a single replica.
func (q *Queries) BurnHandoffJTI(ctx context.Context, arg BurnHandoffJTIParams) (string, error) {
	row := q.db.QueryRow(ctx, burnHandoffJTI, arg.Jti, arg.ExpiresAt)
	var jti string
	err := row.Scan(&jti)
	return jti, err
}

const deleteExpiredHandoffJTIs = `-- name: DeleteExpiredHandoffJTIs :execrows
DELETE FROM handoff_jtis WHERE expires_at < now()
`

// A spent id is only worth remembering until the token it belongs to expires,
// which is 30 seconds. Swept periodically; without it the table grows by one row
// per cross-host login indefinitely.
func (q *Queries) DeleteExpiredHandoffJTIs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredHandoffJTIs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
