// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleService = `-- name: AssignRoleService :exec
INSERT INTO role_services (role_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleServiceParams struct {
	RoleID    uuid.UUID
	ServiceID uuid.UUID
}

func (q *Queries) AssignRoleService(ctx context.Context, arg AssignRoleServiceParams) error {
	_, err := q.db.Exec(ctx, assignRoleService, arg.RoleID, arg.ServiceID)
	return err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignUserRoleParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT count(DISTINCT ur.user_id)
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE r.name = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoles = `-- name: CountRoles :one
SELECT count(*) FROM roles
`

func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersInRole = `-- name: CountUsersInRole :one
SELECT count(*) FROM user_roles WHERE role_id = $1
`

func (q *Queries) CountUsersInRole(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersInRole, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, is_system)
VALUES ($1, $2, $3)
RETURNING id, name, description, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string
	Description string
	IsSystem    bool
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.IsSystem)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND is_system = false
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, is_system, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, is_system, created_at, updated_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT rp.permission
FROM role_permissions rp
JOIN user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
ORDER BY rp.permission ASC
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRoleIDs = `-- name: GetUserRoleIDs :many
SELECT role_id FROM user_roles WHERE user_id = $1
`

func (q *Queries) GetUserRoleIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserRoleIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT INTO role_permissions (role_id, permission)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertRolePermissionParams struct {
	RoleID     uuid.UUID
	Permission string
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, insertRolePermission, arg.RoleID, arg.Permission)
	return err
}

const listAllServicesWithRolesForCache = `-- name: ListAllServicesWithRolesForCache :many
SELECT
    s.id,
    s.title,
    s.description,
    s.service_url,
    s.domain,
    s.headers,
    s.created_at,
    s.updated_at,
    COALESCE(
        (SELECT array_agg(rs.role_id) FROM role_services rs WHERE rs.service_id = s.id),
        ARRAY[]::uuid[]
    )::uuid[] AS role_ids
FROM services s
`

type ListAllServicesWithRolesForCacheRow struct {
	ID          uuid.UUID
	Title       string
	Description string
	ServiceUrl  string
	Domain      string
	Headers     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	RoleIds     []uuid.UUID
}

func (q *Queries) ListAllServicesWithRolesForCache(ctx context.Context) ([]ListAllServicesWithRolesForCacheRow, error) {
	rows, err := q.db.Query(ctx, listAllServicesWithRolesForCache)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllServicesWithRolesForCacheRow
	for rows.Next() {
		var i ListAllServicesWithRolesForCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ServiceUrl,
			&i.Domain,
			&i.Headers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT permission FROM role_permissions
WHERE role_id = $1
ORDER BY permission ASC
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleServices = `-- name: ListRoleServices :many
SELECT s.id, s.title, s.description, s.service_url, s.domain, s.headers, s.created_at, s.updated_at
FROM services s
JOIN role_services rs ON rs.service_id = s.id
WHERE rs.role_id = $1
ORDER BY s.created_at ASC, s.id ASC
`

func (q *Queries) ListRoleServices(ctx context.Context, roleID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listRoleServices, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ServiceUrl,
			&i.Domain,
			&i.Headers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, is_system, created_at, updated_at FROM roles
ORDER BY is_system DESC, name ASC, id ASC
LIMIT $2::int OFFSET $1::int
`

type ListRolesParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRoles = `-- name: ListServiceRoles :many
SELECT r.id, r.name, r.description, r.is_system, r.created_at, r.updated_at
FROM roles r
JOIN role_services rs ON rs.role_id = r.id
WHERE rs.service_id = $1
ORDER BY r.name ASC
`

func (q *Queries) ListServiceRoles(ctx context.Context, serviceID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listServiceRoles, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForUser = `-- name: ListServicesForUser :many
SELECT DISTINCT s.id, s.title, s.description, s.service_url, s.domain, s.headers, s.created_at, s.updated_at
FROM services s
JOIN role_services rs ON rs.service_id = s.id
JOIN user_roles ur ON ur.role_id = rs.role_id
WHERE ur.user_id = $1
ORDER BY s.title ASC, s.id ASC
`

func (q *Queries) ListServicesForUser(ctx context.Context, userID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ServiceUrl,
			&i.Domain,
			&i.Headers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.name, r.description, r.is_system, r.created_at, r.updated_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.is_system DESC, r.name ASC
`

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInRole = `-- name: ListUsersInRole :many
SELECT u.id, u.username, u.email, u.first_name, u.last_name, u.password_hash, u.created_at, u.updated_at
FROM users u
JOIN user_roles ur ON ur.user_id = u.id
WHERE ur.role_id = $1
ORDER BY u.created_at ASC, u.id ASC
LIMIT $3::int OFFSET $2::int
`

type ListUsersInRoleParams struct {
	RoleID uuid.UUID
	Off    int32
	Lim    int32
}

func (q *Queries) ListUsersInRole(ctx context.Context, arg ListUsersInRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersInRole, arg.RoleID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRoleService = `-- name: RevokeRoleService :exec
DELETE FROM role_services WHERE role_id = $1 AND service_id = $2
`

type RevokeRoleServiceParams struct {
	RoleID    uuid.UUID
	ServiceID uuid.UUID
}

func (q *Queries) RevokeRoleService(ctx context.Context, arg RevokeRoleServiceParams) error {
	_, err := q.db.Exec(ctx, revokeRoleService, arg.RoleID, arg.ServiceID)
	return err
}

const revokeUserRole = `-- name: RevokeUserRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RevokeUserRoleParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error {
	_, err := q.db.Exec(ctx, revokeUserRole, arg.UserID, arg.RoleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_system, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.ID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
