// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFilteredServices = `-- name: CountFilteredServices :one
SELECT count(*) FROM services
WHERE (
    $1::text IS NULL
    OR title ILIKE '%' || $1::text || '%'
    OR description ILIKE '%' || $1::text || '%'
    OR domain ILIKE '%' || $1::text || '%'
    OR service_url ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountFilteredServices(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countFilteredServices, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServices = `-- name: CountServices :one
SELECT count(*) FROM services
`

func (q *Queries) CountServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (title, description, service_url, domain, headers, preserve_host, passthrough_errors, max_body_size, read_timeout_secs, write_timeout_secs, dial_timeout_secs)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, title, description, service_url, domain, headers, created_at, updated_at, signing_secret, preserve_host, passthrough_errors, max_body_size, read_timeout_secs, write_timeout_secs, dial_timeout_secs
`

type CreateServiceParams struct {
	Title             string
	Description       string
	ServiceUrl        string
	Domain            string
	Headers           []byte
	PreserveHost      bool
	PassthroughErrors bool
	MaxBodySize       int64
	ReadTimeoutSecs   int32
	WriteTimeoutSecs  int32
	DialTimeoutSecs   int32
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Title,
		arg.Description,
		arg.ServiceUrl,
		arg.Domain,
		arg.Headers,
		arg.PreserveHost,
		arg.PassthroughErrors,
		arg.MaxBodySize,
		arg.ReadTimeoutSecs,
		arg.WriteTimeoutSecs,
		arg.DialTimeoutSecs,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServiceUrl,
		&i.Domain,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SigningSecret,
		&i.PreserveHost,
		&i.PassthroughErrors,
		&i.MaxBodySize,
		&i.ReadTimeoutSecs,
		&i.WriteTimeoutSecs,
		&i.DialTimeoutSecs,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByDomain = `-- name: GetServiceByDomain :one
SELECT id, title, description, service_url, domain, headers, created_at, updated_at, signing_secret, preserve_host, passthrough_errors, max_body_size, read_timeout_secs, write_timeout_secs, dial_timeout_secs FROM services WHERE domain = $1
`

func (q *Queries) GetServiceByDomain(ctx context.Context, domain string) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByDomain, domain)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServiceUrl,
		&i.Domain,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SigningSecret,
		&i.PreserveHost,
		&i.PassthroughErrors,
		&i.MaxBodySize,
		&i.ReadTimeoutSecs,
		&i.WriteTimeoutSecs,
		&i.DialTimeoutSecs,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, title, description, service_url, domain, headers, created_at, updated_at, signing_secret, preserve_host, passthrough_errors, max_body_size, read_timeout_secs, write_timeout_secs, dial_timeout_secs FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServiceUrl,
		&i.Domain,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SigningSecret,
		&i.PreserveHost,
		&i.PassthroughErrors,
		&i.MaxBodySize,
		&i.ReadTimeoutSecs,
		&i.WriteTimeoutSecs,
		&i.DialTimeoutSecs,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, title, description, service_url, domain, headers, created_at, updated_at, signing_secret, preserve_host, passthrough_errors, max_body_size, read_timeout_secs, write_timeout_secs, dial_timeout_secs FROM services
WHERE (
    $1::text IS NULL
    OR title ILIKE '%' || $1::text || '%'
    OR description ILIKE '%' || $1::text || '%'
    OR domain ILIKE '%' || $1::text || '%'
    OR service_url ILIKE '%' || $1::text || '%'
)
ORDER BY created_at ASC, id ASC
LIMIT $3::int OFFSET $2::int
`

type ListServicesParams struct {
	Search pgtype.Text
	Off    int32
	Lim    int32
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ServiceUrl,
			&i.Domain,
			&i.Headers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SigningSecret,
			&i.PreserveHost,
			&i.PassthroughErrors,
			&i.MaxBodySize,
			&i.ReadTimeoutSecs,
			&i.WriteTimeoutSecs,
			&i.DialTimeoutSecs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateServiceSigningSecret = `-- name: RotateServiceSigningSecret :one
UPDATE services
SET signing_secret = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, service_url, domain, headers, created_at, updated_at, signing_secret, preserve_host, passthrough_errors, max_body_size, read_timeout_secs, write_timeout_secs, dial_timeout_secs
`

type RotateServiceSigningSecretParams struct {
	ID            uuid.UUID
	SigningSecret []byte
}

func (q *Queries) RotateServiceSigningSecret(ctx context.Context, arg RotateServiceSigningSecretParams) (Service, error) {
	row := q.db.QueryRow(ctx, rotateServiceSigningSecret, arg.ID, arg.SigningSecret)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServiceUrl,
		&i.Domain,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SigningSecret,
		&i.PreserveHost,
		&i.PassthroughErrors,
		&i.MaxBodySize,
		&i.ReadTimeoutSecs,
		&i.WriteTimeoutSecs,
		&i.DialTimeoutSecs,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET title = $2,
    description = $3,
    service_url = $4,
    domain = $5,
    headers = $6,
    preserve_host = $7,
    passthrough_errors = $8,
    max_body_size = $9,
    read_timeout_secs = $10,
    write_timeout_secs = $11,
    dial_timeout_secs = $12,
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, service_url, domain, headers, created_at, updated_at, signing_secret, preserve_host, passthrough_errors, max_body_size, read_timeout_secs, write_timeout_secs, dial_timeout_secs
`

type UpdateServiceParams struct {
	ID                uuid.UUID
	Title             string
	Description       string
	ServiceUrl        string
	Domain            string
	Headers           []byte
	PreserveHost      bool
	PassthroughErrors bool
	MaxBodySize       int64
	ReadTimeoutSecs   int32
	WriteTimeoutSecs  int32
	DialTimeoutSecs   int32
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ServiceUrl,
		arg.Domain,
		arg.Headers,
		arg.PreserveHost,
		arg.PassthroughErrors,
		arg.MaxBodySize,
		arg.ReadTimeoutSecs,
		arg.WriteTimeoutSecs,
		arg.DialTimeoutSecs,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServiceUrl,
		&i.Domain,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SigningSecret,
		&i.PreserveHost,
		&i.PassthroughErrors,
		&i.MaxBodySize,
		&i.ReadTimeoutSecs,
		&i.WriteTimeoutSecs,
		&i.DialTimeoutSecs,
	)
	return i, err
}
