// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_identities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (provider_id, subject, user_id, email)
VALUES ($1, $2, $3, $4)
RETURNING provider_id, subject, user_id, email, created_at
`

type CreateUserIdentityParams struct {
	ProviderID uuid.UUID
	Subject    string
	UserID     uuid.UUID
	Email      string
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity,
		arg.ProviderID,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ProviderID,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIdentity = `-- name: GetUserIdentity :one
SELECT provider_id, subject, user_id, email, created_at FROM user_identities WHERE provider_id = $1 AND subject = $2
`

type GetUserIdentityParams struct {
	ProviderID uuid.UUID
	Subject    string
}

func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentity, arg.ProviderID, arg.Subject)
	var i UserIdentity
	err := row.Scan(
		&i.ProviderID,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserIdentity = `-- name: UpsertUserIdentity :one
INSERT INTO user_identities (provider_id, subject, user_id, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_id, subject) DO UPDATE
SET email = EXCLUDED.email
RETURNING provider_id, subject, user_id, email, created_at
`

type UpsertUserIdentityParams struct {
	ProviderID uuid.UUID
	Subject    string
	UserID     uuid.UUID
	Email      string
}

func (q *Queries) UpsertUserIdentity(ctx context.Context, arg UpsertUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, upsertUserIdentity,
		arg.ProviderID,
		arg.Subject,
		arg.UserID,
		arg.Email,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ProviderID,
		&i.Subject,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
