// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*)
FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_user_id = $1::uuid)
  AND ($2::text IS NULL OR event_type = $2::text)
  AND ($3::text IS NULL OR target_type = $3::text)
  AND ($4::uuid IS NULL OR target_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR created_at < $6::timestamptz)
`

type CountAuditLogsParams struct {
	ActorUserID uuid.NullUUID
	EventType   pgtype.Text
	TargetType  pgtype.Text
	TargetID    uuid.NullUUID
	FromTs      pgtype.Timestamptz
	ToTs        pgtype.Timestamptz
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorUserID,
		arg.EventType,
		arg.TargetType,
		arg.TargetID,
		arg.FromTs,
		arg.ToTs,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAuditLogsBefore = `-- name: DeleteAuditLogsBefore :execrows
DELETE FROM audit_logs WHERE created_at < $1
`

func (q *Queries) DeleteAuditLogsBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuditLogsBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (
    event_type,
    actor_user_id,
    actor_username,
    target_type,
    target_id,
    target_name,
    client_ip,
    user_agent,
    metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, created_at, event_type, actor_user_id, actor_username, target_type, target_id, target_name, client_ip, user_agent, metadata
`

type InsertAuditLogParams struct {
	EventType     string
	ActorUserID   uuid.NullUUID
	ActorUsername string
	TargetType    string
	TargetID      uuid.NullUUID
	TargetName    string
	ClientIp      string
	UserAgent     string
	Metadata      []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.EventType,
		arg.ActorUserID,
		arg.ActorUsername,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.ClientIp,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.EventType,
		&i.ActorUserID,
		&i.ActorUsername,
		&i.TargetType,
		&i.TargetID,
		&i.TargetName,
		&i.ClientIp,
		&i.UserAgent,
		&i.Metadata,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, created_at, event_type, actor_user_id, actor_username, target_type, target_id, target_name, client_ip, user_agent, metadata
FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_user_id = $1::uuid)
  AND ($2::text IS NULL OR event_type = $2::text)
  AND ($3::text IS NULL OR target_type = $3::text)
  AND ($4::uuid IS NULL OR target_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR created_at < $6::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $8::int OFFSET $7::int
`

type ListAuditLogsParams struct {
	ActorUserID uuid.NullUUID
	EventType   pgtype.Text
	TargetType  pgtype.Text
	TargetID    uuid.NullUUID
	FromTs      pgtype.Timestamptz
	ToTs        pgtype.Timestamptz
	Off         int32
	Lim         int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorUserID,
		arg.EventType,
		arg.TargetType,
		arg.TargetID,
		arg.FromTs,
		arg.ToTs,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EventType,
			&i.ActorUserID,
			&i.ActorUsername,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.ClientIp,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
