// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description string
	IsSystem    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RolePermission struct {
	RoleID     uuid.UUID
	Permission string
}

type RoleService struct {
	RoleID    uuid.UUID
	ServiceID uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Service struct {
	ID          uuid.UUID
	Title       string
	Description string
	ServiceUrl  string
	Domain      string
	Headers     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type SsoProvider struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	IssuerUrl    string
	ClientID     string
	ClientSecret string
	Scopes       string
	Enabled      bool
	AllowSignup  bool
	LinkByEmail  bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	FirstName    string
	LastName     string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserIdentity struct {
	ProviderID uuid.UUID
	Subject    string
	UserID     uuid.UUID
	Email      string
	CreatedAt  pgtype.Timestamptz
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}
