// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso_providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countSSOProviders = `-- name: CountSSOProviders :one
SELECT count(*) FROM sso_providers
`

func (q *Queries) CountSSOProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSSOProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSSOProvider = `-- name: CreateSSOProvider :one
INSERT INTO sso_providers (slug, name, issuer_url, client_id, client_secret, scopes, enabled, allow_signup, link_by_email)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, slug, name, issuer_url, client_id, client_secret, scopes, enabled, allow_signup, link_by_email, created_at, updated_at
`

type CreateSSOProviderParams struct {
	Slug         string
	Name         string
	IssuerUrl    string
	ClientID     string
	ClientSecret string
	Scopes       string
	Enabled      bool
	AllowSignup  bool
	LinkByEmail  bool
}

func (q *Queries) CreateSSOProvider(ctx context.Context, arg CreateSSOProviderParams) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, createSSOProvider,
		arg.Slug,
		arg.Name,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
		arg.AllowSignup,
		arg.LinkByEmail,
	)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.LinkByEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSSOProvider = `-- name: DeleteSSOProvider :exec
DELETE FROM sso_providers WHERE id = $1
`

func (q *Queries) DeleteSSOProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSOProvider, id)
	return err
}

const getSSOProviderByID = `-- name: GetSSOProviderByID :one
SELECT id, slug, name, issuer_url, client_id, client_secret, scopes, enabled, allow_signup, link_by_email, created_at, updated_at FROM sso_providers WHERE id = $1
`

func (q *Queries) GetSSOProviderByID(ctx context.Context, id uuid.UUID) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, getSSOProviderByID, id)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.LinkByEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSOProviderBySlug = `-- name: GetSSOProviderBySlug :one
SELECT id, slug, name, issuer_url, client_id, client_secret, scopes, enabled, allow_signup, link_by_email, created_at, updated_at FROM sso_providers WHERE slug = $1
`

func (q *Queries) GetSSOProviderBySlug(ctx context.Context, slug string) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, getSSOProviderBySlug, slug)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.LinkByEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledSSOProviders = `-- name: ListEnabledSSOProviders :many
SELECT id, slug, name FROM sso_providers
WHERE enabled = true
ORDER BY created_at ASC, id ASC
`

type ListEnabledSSOProvidersRow struct {
	ID   uuid.UUID
	Slug string
	Name string
}

func (q *Queries) ListEnabledSSOProviders(ctx context.Context) ([]ListEnabledSSOProvidersRow, error) {
	rows, err := q.db.Query(ctx, listEnabledSSOProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledSSOProvidersRow
	for rows.Next() {
		var i ListEnabledSSOProvidersRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSOProviders = `-- name: ListSSOProviders :many
SELECT id, slug, name, issuer_url, client_id, client_secret, scopes, enabled, allow_signup, link_by_email, created_at, updated_at FROM sso_providers
ORDER BY created_at ASC, id ASC
LIMIT $2::int OFFSET $1::int
`

type ListSSOProvidersParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListSSOProviders(ctx context.Context, arg ListSSOProvidersParams) ([]SsoProvider, error) {
	rows, err := q.db.Query(ctx, listSSOProviders, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoProvider
	for rows.Next() {
		var i SsoProvider
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IssuerUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.Scopes,
			&i.Enabled,
			&i.AllowSignup,
			&i.LinkByEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSSOProvider = `-- name: UpdateSSOProvider :one
UPDATE sso_providers
SET slug = $2,
    name = $3,
    issuer_url = $4,
    client_id = $5,
    client_secret = $6,
    scopes = $7,
    enabled = $8,
    allow_signup = $9,
    link_by_email = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, name, issuer_url, client_id, client_secret, scopes, enabled, allow_signup, link_by_email, created_at, updated_at
`

type UpdateSSOProviderParams struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	IssuerUrl    string
	ClientID     string
	ClientSecret string
	Scopes       string
	Enabled      bool
	AllowSignup  bool
	LinkByEmail  bool
}

func (q *Queries) UpdateSSOProvider(ctx context.Context, arg UpdateSSOProviderParams) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, updateSSOProvider,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.IssuerUrl,
		arg.ClientID,
		arg.ClientSecret,
		arg.Scopes,
		arg.Enabled,
		arg.AllowSignup,
		arg.LinkByEmail,
	)
	var i SsoProvider
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IssuerUrl,
		&i.ClientID,
		&i.ClientSecret,
		&i.Scopes,
		&i.Enabled,
		&i.AllowSignup,
		&i.LinkByEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
